# Generated by Django 4.0.3 on 2022-03-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('market_cap_rank', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('current_price', models.FloatField()),
                ('high_24h', models.FloatField()),
                ('low_24h', models.FloatField()),
                ('price_change_24h', models.FloatField()),
                ('price_change_percentage_24h', models.FloatField()),
                ('market_cap_change_24h', models.FloatField()),
                ('market_cap_change_percentage_24h', models.FloatField()),
            ],
        ),
    ]
