# Generated by Django 4.0.3 on 2022-03-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coin',
            table='coins',
        ),
    ]
