# Generated by Django 4.0.3 on 2022-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_coin_current_price_alter_coin_high_24h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
